repository: https://github.com/flaport/flayout
output: web
topnav_title: FLayout
site_title: FLayout
company_name: Floris Laporte
description: FLayout
use_math: true
google_analytics:
google_search:
host: 127.0.0.1
port: 4000

exclude:
  - .idea/
  - .vscode/
  - .gitignore
  - vendor

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars:
- home_sidebar

plugins:
    - jekyll-remote-theme

remote_theme: fastai/nbdev-jekyll-theme
baseurl: /flayout/
