# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ALPHA": "01_bokeh.ipynb",
         "RED": "01_bokeh.ipynb",
         "GREEN": "01_bokeh.ipynb",
         "BLUE": "01_bokeh.ipynb",
         "C0": "01_bokeh.ipynb",
         "C1": "01_bokeh.ipynb",
         "C2": "01_bokeh.ipynb",
         "C3": "01_bokeh.ipynb",
         "C4": "01_bokeh.ipynb",
         "C5": "01_bokeh.ipynb",
         "C6": "01_bokeh.ipynb",
         "C7": "01_bokeh.ipynb",
         "C8": "01_bokeh.ipynb",
         "C9": "01_bokeh.ipynb",
         "get_lyp_path": "01_bokeh.ipynb",
         "LayerProperty": "01_bokeh.ipynb",
         "LayerProperties": "01_bokeh.ipynb",
         "read_lyp": "01_bokeh.ipynb",
         "get_lyp": "01_bokeh.ipynb",
         "new_plot": "01_bokeh.ipynb",
         "adjust_plot": "01_bokeh.ipynb",
         "draw_polys": "01_bokeh.ipynb",
         "draw_poly": "01_bokeh.ipynb",
         "draw_path": "01_bokeh.ipynb",
         "draw_vector": "01_bokeh.ipynb",
         "draw_box": "01_bokeh.ipynb"}

modules = ["ext/bokeh.py"]

doc_url = "https://flaport.gitlab.io/flaport/flayout/"

git_url = "https://gitlab.com/flaport/flayout/tree/master/"

def custom_doc_links(name): return None
