# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://flaport.gitlab.io/flaport/flayout/"

git_url = "https://gitlab.com/flaport/flayout/tree/master/"

def custom_doc_links(name): return None
