# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ALPHA": "01_bokeh.ipynb",
         "RED": "01_bokeh.ipynb",
         "GREEN": "01_bokeh.ipynb",
         "BLUE": "01_bokeh.ipynb",
         "C0": "01_bokeh.ipynb",
         "C1": "01_bokeh.ipynb",
         "C2": "01_bokeh.ipynb",
         "C3": "01_bokeh.ipynb",
         "C4": "01_bokeh.ipynb",
         "C5": "01_bokeh.ipynb",
         "C6": "01_bokeh.ipynb",
         "C7": "01_bokeh.ipynb",
         "C8": "01_bokeh.ipynb",
         "C9": "01_bokeh.ipynb",
         "get_lyp_path": "01_bokeh.ipynb",
         "LayerProperty": "01_bokeh.ipynb",
         "LayerProperties": "01_bokeh.ipynb",
         "read_lyp": "01_bokeh.ipynb",
         "get_lyp": "01_bokeh.ipynb",
         "new_plot": "01_bokeh.ipynb",
         "adjust_plot": "01_bokeh.ipynb",
         "draw_polys": "01_bokeh.ipynb",
         "draw_poly": "01_bokeh.ipynb",
         "draw_path": "01_bokeh.ipynb",
         "draw_point": "01_bokeh.ipynb",
         "draw_vector": "01_bokeh.ipynb",
         "draw_box": "01_bokeh.ipynb",
         "draw_cell": "01_bokeh.ipynb",
         "draw_inst": "01_bokeh.ipynb",
         "draw_layout": "01_bokeh.ipynb",
         "html_repr": "02_notebook.ipynb",
         "DoesNotExist": "03_cell.ipynb",
         "SUPPORTED": "03_cell.ipynb",
         "MAX_DEPTH": "03_cell.ipynb",
         "ON_SAME_NAME_DOC": "03_cell.ipynb",
         "Reference": "03_cell.ipynb",
         "LibReference": "03_cell.ipynb",
         "PCellReference": "03_cell.ipynb",
         "PCellLibReference": "03_cell.ipynb",
         "reference": "03_cell.ipynb",
         "copy_tree": "03_cell.ipynb",
         "add_cells_to_layout": "03_cell.ipynb",
         "add_pcells_to_layout": "03_cell.ipynb",
         "add_lib_pcell_to_layout": "03_cell.ipynb",
         "add_lib_cell_to_layout": "03_cell.ipynb",
         "add_cell_to_layout": "03_cell.ipynb",
         "Point": "04_factories.ipynb",
         "Points": "04_factories.ipynb",
         "Shape": "04_factories.ipynb",
         "layer": "04_factories.ipynb",
         "point": "04_factories.ipynb",
         "vector": "04_factories.ipynb",
         "polygon": "04_factories.ipynb",
         "path": "04_factories.ipynb"}

modules = ["bokeh.py",
           "notebook.py",
           "cell.py",
           "factories.py"]

doc_url = "https://flaport.gitlab.io/flaport/flayout/"

git_url = "https://gitlab.com/flaport/flayout/tree/master/"

def custom_doc_links(name): return None
