# AUTOGENERATED! DO NOT EDIT! File to edit: source/99_example_lib.ipynb (unless otherwise specified).

__all__ = ['rectangle', 'square', 'example_lib']

# Internal Cell
import pya
import flayout as fl

# Cell
@fl.pcell
def rectangle(
    name="rectangle",
    width: float = 1.0,
    height: float = 0.5,
    layer: pya.LayerInfo = pya.LayerInfo(1, 0),
):
    rect = fl.polygon(hull=[(-width/2, -height/2), (width/2, -height/2), (width/2, height/2), (-width/2, height/2)])
    cell = fl.cell(name, shapes={layer: [rect]})
    return cell

# Cell
@fl.pcell
def square(
    name="square",
    width: float = 0.5,
    layer: pya.LayerInfo = pya.LayerInfo(1, 0),
):
    square = fl.polygon(hull=[(-width/2, -width/2), (width/2, -width/2), (width/2, width/2), (-width/2, width/2)])
    cell = fl.cell(name, shapes={layer: [square]})
    return cell

# Cell
example_lib = fl.library(
    "flayout_example_library",
    pcells=[rectangle, square],
    cells=[],
    description="FLayout Example Library",
)