# AUTOGENERATED! DO NOT EDIT! File to edit: source/02_notebook.ipynb (unless otherwise specified).

__all__ = ['html_repr']

# Internal Cell
import flayout.bokeh as flbk
import pya
from bokeh.embed import file_html
from bokeh.io import output_notebook
from bokeh.resources import CDN

try:
    IPYTHON = get_ipython()  # type: ignore
    output_notebook(hide_banner=True)
except NameError:
    IPYTHON = None

# Cell
def html_repr(func, types):
    for cls in types:

        def registered(obj):
            plot = func(None, obj)
            html = file_html(plot, CDN)
            return html

        if IPYTHON is not None:
            fmtr = IPYTHON.display_formatter.formatters["text/html"]
            fmtr.for_type(cls, registered)

# Cell
html_repr(flbk.draw_point, [pya.DPoint, pya.Point])
html_repr(flbk.draw_vector, [pya.DVector, pya.Vector])
html_repr(flbk.draw_path, [pya.Path, pya.DPath])
html_repr(flbk.draw_poly, [pya.DSimplePolygon, pya.SimplePolygon, pya.DPolygon, pya.Polygon])
html_repr(flbk.draw_box, [pya.Box, pya.DBox])
html_repr(flbk.draw_cell, [pya.Cell])
html_repr(flbk.draw_inst, [pya.Instance])
html_repr(flbk.draw_layout, [pya.Layout])